[[redirects]]
  from = "https://remarkable-unicorn-5e00d9.netlify.app/people/test"
  to = "https://remarkable-unicorn-5e00d9.netlify.app/people/test"



[[redirects]]
  from = "/*"
  to = "https://remarkable-unicorn-5e00d9.netlify.app/"

